Deprecate conversion functions
neo4j-contrib/neo4j-apoc-procedures pull request #1899
Opened 2021-05-10 15:49 UTC by mnd999

Deprecate conversion functions that have moved into product as part of 4.3

## Proposed Changes:

Deprecate the following conversion functions:

- apoc.convert.toFloat(value)
- apoc.convert.toInteger(value) 
- apoc.convert.toString(value)
- apoc.convert.toBoolean(value)
- apoc.convert.toIntList(value)
- apoc.convert.toStringList(value)
- apoc.convert.toBooleanList(value)

2021-05-11 14:21 UTC, Lojjs requested changes

2021-05-12 12:48 UTC, mnd999 commented on docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.toBoolean.adoc
> +|`datetime("2000-01-01T00:00:00.000+0000")` footnote:composite[]|`true`|Error|`null`
Had added it to toString and toBoolean as they are interesting. The others are just null or error.

2021-05-14 07:44 UTC, Lojjs approved these changes

2021-05-24 13:31 UTC, JMHReif commented
Hello! Sorry for the delay @mnd999. Florent and I will take a look at this in our APOC meeting this week. Thanks for contributing!

2021-05-25 08:43 UTC, mnd999 commented
@JMHReif I think this will change again, PM are discussing whether to reduce the scope of the deprecation.

2021-05-26 03:35 UTC, JMHReif commented
Ok, that makes sense. We can leave this open until something is confirmed with PM then?

2021-05-26 15:33 UTC, mnd999 commented
@JMHReif PM have confirmed they're okay with the changes, so this is good to review now.

2021-05-27 15:20 UTC, fbiville approved these changes

2021-05-27 15:20 UTC, merged