Fixes #577: return apoc.nodes.count(['User'])
neo4j-contrib/neo4j-apoc-procedures pull request #2277
Opened 2021-11-03 12:23 UTC by vga91

Fixes #577

2021-11-05 20:38 UTC, jexp commented on docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.meta.nodes-lite.csv
> +¦apoc.meta.nodes.count(nodes = [] :: LIST? OF STRING?, config = {} :: MAP?) :: (INTEGER?)
aren't these files generated and should not be checked in? everything in generated documentation.

2021-11-05 20:40 UTC, jexp commented on docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.nodes.count.adoc
> +|===
I don't think the implementation is what I expected it to be, I expected one result (row) per label

2021-11-05 20:40 UTC, jexp requested changes
I don't think the implementation is what I expected it to be, I expected one result (row) per label

2021-12-13 16:47 UTC, vga91 commented
> I don't think the implementation is what I expected it to be, I expected one result (row) per label

@jexp Sorry, I thought I answered 😅
I changed the implementation (1 row per label) and deleted some extra auto-generated files.

2022-01-13 12:10 UTC, merged