Update to not use deprecated index and constraint syntax
neo4j-contrib/neo4j-apoc-procedures pull request #2385
Opened 2021-12-02 16:50 UTC by Hunterness

They are currently in progress of being removed and are therefore in need of being updated

2021-12-06 08:15 UTC, HannesSandberg requested changes
I have problem with building this branch, maybe you could help me out.

Found some more places to update:

`CREATE CONSTRAINT ON ... ASSERT` in `SchemasTest.java`

`db.index.fulltext` in `SignatureTest.java` and `signatures.csv`

2021-12-06 08:40 UTC, Hunterness commented on core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
>          return db.executeTransactionally("CALL db.indexes()", Collections.emptyMap(), result -> result.stream()
no this method is the one causing https://trello.com/c/KJUMznPU/2751-apoc-failures-due-to-removal-of-dbindexes and can not yet be removed without breaking things

2021-12-06 08:41 UTC, Hunterness commented
> `db.index.fulltext` in `SignatureTest.java` and `signatures.csv`

is it the create or query methods? cause it is only create/drop that are being removed, the query ones are still valid

2021-12-06 08:42 UTC, HannesSandberg commented on core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
>          return db.executeTransactionally("CALL db.indexes()", Collections.emptyMap(), result -> result.stream()
Ok. I see

2021-12-06 08:43 UTC, HannesSandberg commented
> > db.index.fulltext in SignatureTest.java and signatures.csv

> is it the create or query methods? cause it is only create/drop that are being removed, the query ones are still valid

Ok, these are not create so should be fine then

2021-12-29 15:30 UTC, conker84 commented
Hi @Hunterness what is the status of this one?

2022-01-07 11:11 UTC, Hunterness commented
@conker84 Not really sure, I don't know why it doesn't build but I would like to see a green build before merging to know I have fixed things properly (I had issues with building things locally in general so I can't even check it myself)

2022-02-14 08:07 UTC, HannesSandberg approved these changes
Lgtm. I get a few test failures when building this locally. But as far as I can tell it has nothing to do with these changes.

2022-02-14 08:30 UTC, Hunterness commented
@conker84 I managed got get it to build locally, and all tests I have changed seems to work now so I'll merge and hope nothing else breaks

2022-02-14 09:32 UTC, merged