Fixes #2933: Add configurations for apoc.load.html via selenium browser
neo4j-contrib/neo4j-apoc-procedures pull request #2990
Opened 2022-06-15 13:02 UTC by vga91

Fixes #2933

2022-06-30 12:07 UTC, ncordon commented on full/src/test/java/apoc/load/LoadHtmlTest.java
> +                        "config", map("browser", browser, "driverVersion", "0.3.0")),
This needs to be 0.30.0 @vga91

2022-06-30 12:21 UTC, ncordon requested changes
Please change the Firefox driver version as before

2022-06-30 13:28 UTC, vga91 commented on full/src/test/java/apoc/load/LoadHtmlTest.java
> +                        "config", map("browser", browser, "driverVersion", "0.3.0")),
Changed

2022-07-01 16:23 UTC, ncordon approved these changes

2022-07-01 17:13 UTC, merged