Added var. adoc and test for meta configs
neo4j-contrib/neo4j-apoc-procedures pull request #3032
Opened 2022-07-05 16:15 UTC by vga91

Added adoc test meta configs

- `maxRels` test config
- `excludes` test and adoc config
- `includeLabels`/`excludeLabels`/`includeRels`/`excludeRels` adocs
- changed `assertEquals(true,` with `assertTrue`

2022-07-07 11:50 UTC, nadja-muller requested changes

2022-07-13 11:05 UTC, vga91 commented on docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.data.adoc
> -| maxRels | Long | 100 | number of relationships to sample per relationship type
Yes, it's not so evident. The `maxRels` is part of `MetaConfig` common class, but in the apoc.meta.data this attribute is not used (that is, there isn't a `metaConfig.getMaxRels()` in the implementation), unlike e.g the `apoc.meta.graph`.
Indeed, after a deeper double-check, I noticed that even other configs (except for `sample`) are not used. I've removed them too.

2022-07-13 11:07 UTC, vga91 commented
@nadja-muller Thanks for the review. I pushed the review changes and added some small missing detail about `sample` config.

2022-07-13 14:14 UTC, nadja-muller approved these changes

2022-07-13 14:29 UTC, merged