[gRNAet7B] Fixes trigger procedures in clusters for neo4j 5.x (extended part)
neo4j-contrib/neo4j-apoc-procedures pull request #3330
Opened 2022-11-22 22:37 UTC by vga91

TODO: Waiting for https://github.com/neo4j/apoc/pull/250
Change `.gitmodules` branch to dev when the pr is merged

2022-11-23 10:23 UTC, ncordon requested changes
Probably these tests should be moved to core?

2022-11-28 08:54 UTC, vga91 commented
> Probably these tests should be moved to core?

They are on `extended` because leverage on extended functions, e.g. `apoc.trigger.nodesByLabel`.

2023-01-05 17:34 UTC, ncordon commented on .gitmodules
> +	branch = dev-fix-trigger-procedures
This should always point to `dev`

2023-01-05 17:38 UTC, ncordon reviewed
It looks good, happy to approve once the branch of the submodule has been changed

2023-01-09 11:27 UTC, closed without merging

2023-01-11 08:36 UTC, vga91 commented
Closed in favor of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3391